name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1
          POSTGRES_DB: leetcode
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root dependencies and Lerna
        run: |
          npm install
          npx lerna bootstrap

      # Backend setup and tests
      - name: Wait for PostgreSQL
        run: |
          until pg_isready --host=localhost --port=5432 --username=postgres; do
            echo "Waiting for postgres..."
            sleep 5
          done

      - name: Run Prisma Migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: postgres://postgres:1@localhost:5432/leetcode
        working-directory: ./services/server

      - name: Run Backend Tests
        run: npm run test
        env:
          DATABASE_URL: postgres://postgres:1@localhost:5432/leetcode
        working-directory: ./services/server

      # Frontend setup and build
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./services/lk-vue

      - name: Build frontend
        run: npm run build
        working-directory: ./services/lk-vue

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -p 49252 user@7552d3ce81f9.vps.myjino.ru 'cd /home/user/efremov-ruslan-otus && docker-compose up -d --build'
